### ISSUE TITLE
lowercase table names

### ISSUE THREAD

**Issue by HaroonSaid** [tomasfabian/Kafka.DotNet.ksqlDB#3]
When writing a pull query, how do I specify that the table name is in lowercase

```
return await this.context.CreatePullQuery<ElasticSearchEvent>("table_name")
                 .Where(c => c.Key == key)
                 .GetAsync();
```
converts to uppercase

**Comment by tomasfabian** [comment]
Hi @HaroonSaid,
you have already specified the table name as lowercase in your example, didn't you?
 
```C#
int key = 42;
string query = context.CreatePullQuery<ElasticSearchEvent>(tableName: "table_name")
                 .Where(c => c.Key == key)
                 .ToQueryString();

Console.WriteLine(query);
```

The above mentioned code snippet should print the following query:

```SQL
SELECT * FROM table_name
WHERE Key = 42;
```

What are your expectations, could you please clarify them more precisely?

For example if the table name is "elastic_search_event", you can provide it as the argument for ```CreatePullQuery(string tableName)```.

```C#
context.CreatePullQuery<ElasticSearchEvent>("elastic_search_event")
```

**Comment by HaroonSaid** [comment]
Hi Tomas,

Thanks for the quick reply, 
The query string is: 

```
SELECT * FROM integration_test_ticketing_event_enriched_queryables\nWHERE Key = '1:2';
```
The exception that I see is 
```
Exception while preparing statement: INTEGRATION_TEST_TICKETING_EVENT_ENRICHED_QUERYABLES does not exist.\nStatement: SELECT * FROM integration_test_ticketing_event_enriched_queryables\nWHERE Key = '1:2';\nCaused by: INTEGRATION_TEST_TICKETING_EVENT_ENRICHED_QUERYABLES does not exist.
```
The query should look like 
 ```
SELECT * FROM "integration_test_ticketing_event_enriched_queryables"\nWHERE Key = '1:2';
```

Let me know if you need any more info.

**Comment by HaroonSaid** [comment]
I was able to use backtick in the table name to solve my problem

Thanks
